---
- name: Update Check
  hosts: windows
  gather_facts: false

  tasks:
    - name: Suche nach Updates
      ansible.windows.win_updates:
        state: searched
      register: updates

    - debug:
        msg: "{{ updates.found_update_count }} Updates verfügbar"
